USE QLDienMay
GO
-- TRIGGER
---Them data vao bang, trigger se tu dong tao ID theo thu tu---
---Tao ID NCC----
CREATE TRIGGER TAO_ID_NHA_CUNG_CAP ON NhaCungCap INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENNCC NVARCHAR(50) = (SELECT TenNCC FROM inserted)
	DECLARE @DIACHI NVARCHAR(100) = (SELECT DiaChi FROM inserted)
	DECLARE @MASOTHUE CHAR(10) = (SELECT MaSoThue FROM inserted)

	DECLARE @DEMNCC INT = (SELECT COUNT(MaNCC) FROM NhaCungCap)

	DECLARE @ID CHAR(5) 
	SET @DEMNCC += 1

	DECLARE @CHUOISOKHONG VARCHAR(5) = '0'
	
	DECLARE @I INT = 0
	DECLARE @LENGTHID INT = 5 - (LEN(@DEMNCC) + LEN('CC'))

	WHILE (@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG = @CHUOISOKHONG + '0'
			SET @I += 1;
		END
	SET @ID  = CONCAT('CC',@CHUOISOKHONG,@DEMNCC)
	DECLARE @DEMID INT = (SELECT COUNT(MaNCC) FROM NhaCungCap WHERE MaNCC = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMNCC += 1;

		SET @CHUOISOKHONG = '0'
		SET @I = 0
		SET @LENGTHID = 10 - ((SELECT LEN(@DEMNCC)) + (SELECT LEN('CC')))
		WHILE (@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG = @CHUOISOKHONG + '0'
			SET @I += 1;
		END
		SET @ID  = CONCAT('CC',@CHUOISOKHONG,@DEMNCC)
		SET @DEMID = (SELECT COUNT(MaNCC) FROM NhaCungCap WHERE MaNCC = @ID)
	END
	
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO NhaCungCap(MaNCC,TenNCC,MaSoThue,DiaChi)
		VALUES(@ID,@TENNCC,@MASOTHUE,@DIACHI)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID ThanhPho----
CREATE TRIGGER TAO_ID_THANH_PHO ON ThanhPho INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENTP NVARCHAR(50) = (SELECT TenThanhPho FROM inserted)

	DECLARE @DEMTP INT = (SELECT COUNT(MaThanhPho) FROM ThanhPho)

	DECLARE @ID CHAR(5) 
	SET @DEMTP += 1

	DECLARE @CHUOISOKHONG VARCHAR(5) = '0'
	
	DECLARE @I INT = 0
	DECLARE @LENGTHID INT = 5 - (LEN(@DEMTP) + LEN('TP'))

	WHILE (@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG = @CHUOISOKHONG + '0'
			SET @I += 1;
		END
	SET @ID  = CONCAT('TP',@CHUOISOKHONG,@DEMTP)
	DECLARE @DEMID INT = (SELECT COUNT(MaThanhPho) FROM ThanhPho WHERE MaThanhPho = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMTP += 1;

		SET @CHUOISOKHONG = '0'
		SET @I = 0
		SET @LENGTHID = 10 - ((SELECT LEN(@DEMTP)) + (SELECT LEN('TP')))
		WHILE (@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG = @CHUOISOKHONG + '0'
			SET @I += 1;
		END
		SET @ID  = CONCAT('TP',@CHUOISOKHONG,@DEMTP)
		SET @DEMID = (SELECT COUNT(MaThanhPho) FROM ThanhPho WHERE MaThanhPho = @ID)
	END
	
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO ThanhPho(MaThanhPho,TenThanhPho)
		VALUES(@ID,@TENTP)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID KM----
CREATE TRIGGER TAO_ID_CHO_KHUYEN_MAI ON KhuyenMai INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENKM NVARCHAR(50) = (SELECT TenKM FROM inserted)
	DECLARE @PHANTRAMKM FLOAT = (SELECT PhanTramKhuyenMai FROM inserted)
	DECLARE @NGAYBD DATETIME = (SELECT NgayBatDau FROM inserted)
	DECLARE @NGAYKT DATETIME = (SELECT NgayKetThuc FROM inserted)
	DECLARE @MOTA NVARCHAR(50) = (SELECT MoTa FROM inserted)

	DECLARE @DEMKM INT = (SELECT COUNT(MaKhuyenMai) FROM KhuyenMai)
	DECLARE @I INT = 0
	SET @DEMKM += 1
	DECLARE @ID CHAR(10)

	DECLARE @CHUOISOKHONG VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('KM') + LEN(@DEMKM))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('KM',@CHUOISOKHONG,@DEMKM)
	DECLARE @DEMID INT = (SELECT COUNT(MaKhuyenMai) FROM KhuyenMai WHERE MaKhuyenMai = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMKM += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 8 - (LEN('KM') + LEN(@DEMKM))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('KM',@CHUOISOKHONG,@DEMKM)
		SET @DEMID = (SELECT COUNT(MaKhuyenMai) FROM KhuyenMai WHERE MaKhuyenMai = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO KhuyenMai(MaKhuyenMai,TenKM,PhanTramKhuyenMai,NgayBatDau,NgayKetThuc,MoTa)
		VALUES(@ID,@TENKM,@PHANTRAMKM,@NGAYBD,@NGAYKT,@MOTA)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID DM----
CREATE TRIGGER TAO_ID_CHO_DANH_MUC ON DanhMuc INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENDM NVARCHAR(50) = (SELECT TenDanhMuc FROM inserted)

	DECLARE @DEMDM INT = (SELECT COUNT(MaDanhMuc) FROM DanhMuc)
	DECLARE @I INT = 0
	SET @DEMDM += 1
	DECLARE @ID CHAR(5)

	DECLARE @CHUOISOKHONG VARCHAR(3) = '0'
	DECLARE @LENGTHID INT = 5 - (LEN('DM') + LEN(@DEMDM))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('DM',@CHUOISOKHONG,@DEMDM)
	DECLARE @DEMID INT = (SELECT COUNT(MaDanhMuc) FROM DanhMuc WHERE MaDanhMuc = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMDM += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 5 - (LEN('DM') + LEN(@DEMDM))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('DM',@CHUOISOKHONG,@DEMDM)
		SET @DEMID = (SELECT COUNT(MaDanhMuc) FROM DanhMuc WHERE MaDanhMuc = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO DanhMuc(MaDanhMuc,TenDanhMuc)
		VALUES(@ID,@TENDM)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID cho LOAI---
CREATE TRIGGER TAO_ID_CHO_LOAI ON Loai INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENLOAI NVARCHAR(50) = (SELECT TenLoai FROM inserted)
	DECLARE @MADM CHAR(5) = (SELECT MaDanhMuc FROM inserted)

	DECLARE @DEMLOAI INT = (SELECT COUNT(MaLoai) FROM Loai)
	DECLARE @I INT = 0
	SET @DEMLOAI += 1
	DECLARE @ID CHAR(5)

	DECLARE @CHUOISOKHONG VARCHAR(4) = '0'
	DECLARE @LENGTHID INT = 5 - (LEN('L') + LEN(@DEMLOAI))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('L',@CHUOISOKHONG,@DEMLOAI)
	DECLARE @DEMID INT = (SELECT COUNT(MaLoai) FROM Loai WHERE MaLoai = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMLOAI += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 5 - (LEN('L') + LEN(@DEMLOAI))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('L',@CHUOISOKHONG,@DEMLOAI)
		SET @DEMID = (SELECT COUNT(MaLoai) FROM Loai WHERE MaLoai = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO Loai(MaLoai,TenLoai,MaDanhMuc)
		VALUES(@ID,@TENLOAI,@MADM)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID cho SP---
CREATE TRIGGER TAO_ID_CHO_SAN_PHAM ON SanPham INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENSP NVARCHAR(100) = (SELECT TenSanPham FROM inserted)
	DECLARE @MATH CHAR(5) = (SELECT MaThuongHieu FROM inserted)
	DECLARE @ANHMINHHOA VARCHAR(100) = (SELECT AnhMinhHoa FROM inserted)
	DECLARE @DONGIA DECIMAL(18,2) = (SELECT DonGia FROM inserted)
	DECLARE @MAKM CHAR(10) = (SELECT MaKhuyenMai FROM inserted)

	DECLARE @DEMSP INT = (SELECT COUNT(MaSanPham) FROM SanPham)
	DECLARE @I INT = 0
	SET @DEMSP += 1
	DECLARE @ID CHAR(10)

	DECLARE @CHUOISOKHONG VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('SP') + LEN(@DEMSP))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('SP',@CHUOISOKHONG,@DEMSP)
	DECLARE @DEMID INT = (SELECT COUNT(MaSanPham) FROM SanPham WHERE MaSanPham = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMSP += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('SP') + LEN(@DEMSP))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('SP',@CHUOISOKHONG,@DEMSP)
		SET @DEMID = (SELECT COUNT(MaSanPham) FROM SanPham WHERE MaSanPham = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO SanPham(MaSanPham,TenSanPham,MaThuongHieu,AnhMinhHoa,DonGia,MaKhuyenMai)
		VALUES(@ID,@TENSP,@MATH,@ANHMINHHOA,@DONGIA,@MAKM)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID cho CHUCVU---
CREATE TRIGGER TAO_ID_CHO_CHUC_VU ON ChucVu INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENCV NVARCHAR(50) = (SELECT TenChucVu FROM inserted)

	DECLARE @DEMCV INT = (SELECT COUNT(MaChucVu) FROM ChucVu)
	DECLARE @I INT = 0
	SET @DEMCV += 1
	DECLARE @ID CHAR(5)

	DECLARE @CHUOISOKHONG VARCHAR(3) = '0'
	DECLARE @LENGTHID INT = 5 - (LEN('CV') + LEN(@DEMCV))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('CV',@CHUOISOKHONG,@DEMCV)
	DECLARE @DEMID INT = (SELECT COUNT(MaChucVu) FROM ChucVu WHERE MaChucVu = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMCV += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 5 - (LEN('CV') + LEN(@DEMCV))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('CV',@CHUOISOKHONG,@DEMCV)
		SET @DEMID = (SELECT COUNT(MaChucVu) FROM ChucVu WHERE MaChucVu = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO ChucVu(MaChucVu,TenChucVu)
		VALUES(@ID,@TENCV)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID cho CUAHANG---
CREATE TRIGGER TAO_ID_CHO_CUA_HANG ON CuaHang INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @DIACHI NVARCHAR(100) = (SELECT DiaChi FROM inserted)
	DECLARE @TP CHAR(5) = (SELECT ThanhPho FROM inserted)
	DECLARE @CHTRUONG CHAR(10) = (SELECT CuaHangTruong FROM inserted)
	DECLARE @NGAYTHANHLAP DATETIME = (SELECT NgayThanhLap FROM inserted)

	DECLARE @DEMCH INT = (SELECT COUNT(MaCuaHang) FROM CuaHang)
	DECLARE @I INT = 0
	SET @DEMCH += 1
	DECLARE @ID CHAR(5)

	DECLARE @CHUOISOKHONG VARCHAR(3) = '0'
	DECLARE @LENGTHID INT = 5 - (LEN('CH') + LEN(@DEMCH))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('CH',@CHUOISOKHONG,@DEMCH)
	DECLARE @DEMID INT = (SELECT COUNT(MaCuaHang) FROM CuaHang WHERE MaCuaHang = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMCH += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 5 - (LEN('CH') + LEN(@DEMCH))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('CH',@CHUOISOKHONG,@DEMCH)
		SET @DEMID = (SELECT COUNT(MaCuaHang) FROM CuaHang WHERE MaCuaHang = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO CuaHang(MaCuaHang,DiaChi,ThanhPho,CuaHangTruong,NgayThanhLap)
		VALUES(@ID,@DIACHI,@TP,@CHTRUONG,@NGAYTHANHLAP)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID cho NHANVIEN---
CREATE TRIGGER TAO_ID_CHO_NHAN_VIEN ON NhanVien INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @TENNV NVARCHAR(50) = (SELECT TenNhanVien FROM inserted)
	DECLARE @NGAYSINH DATETIME = (SELECT NgaySinh FROM inserted)
	DECLARE @SDT CHAR(10) = (SELECT SDT FROM inserted)
	DECLARE @EMAIL CHAR(50) = (SELECT Email FROM inserted)
	DECLARE @DIACHI NVARCHAR(100) = (SELECT DiaChi FROM inserted)
	DECLARE @GIOITINH BIT = (SELECT GioiTinh FROM inserted)
	DECLARE @CHUCVU CHAR(5) = (SELECT ChucVu FROM inserted)
	DECLARE @CUAHANG CHAR(5) = (SELECT CuaHang FROM inserted)
	DECLARE @HINHTHUC BIT = (SELECT HinhThuc FROM inserted)
	DECLARE @TAIKHOAN CHAR(50) = (SELECT TaiKhoan FROM inserted)
	DECLARE @MATKHAU CHAR(50) = (SELECT MatKhau FROM inserted)
	DECLARE @TRANGTHAI BIT = (SELECT TrangThai FROM inserted)

	DECLARE @DEMNV INT = (SELECT COUNT(MaNhanVien) FROM NhanVien)
	DECLARE @I INT = 0
	SET @DEMNV += 1
	DECLARE @ID CHAR(10)

	DECLARE @CHUOISOKHONG VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('NV') + LEN(@DEMNV))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('NV',@CHUOISOKHONG,@DEMNV)
	DECLARE @DEMID INT = (SELECT COUNT(MaNhanVien) FROM NhanVien WHERE MaNhanVien = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMNV += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('NV') + LEN(@DEMNV))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('NV',@CHUOISOKHONG,@DEMNV)
		SET @DEMID = (SELECT COUNT(MaNhanVien) FROM NhanVien WHERE MaNhanVien = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO NhanVien(MaNhanVien,TenNhanVien,NgaySinh,SDT,Email,DiaChi,GioiTinh,ChucVu,CuaHang,HinhThuc,TaiKhoan,MatKhau,TrangThai)
		VALUES(@ID,@TENNV,@NGAYSINH,@SDT,@EMAIL,@DIACHI,@GIOITINH,@CHUCVU,@CUAHANG,@HINHTHUC,@TAIKHOAN,@MATKHAU,@TRANGTHAI)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
---Tao ID cho KHO---
CREATE TRIGGER TAO_ID_CHO_KHO ON Kho INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @CUAHANG CHAR(5) = (SELECT MaCuaHang FROM inserted)
	DECLARE @TRUONGKHO CHAR(10) = (SELECT TruongKho FROM inserted)
	DECLARE @DIACHI NVARCHAR(100) = (SELECT DiaChi FROM inserted)
	IF EXISTS(SELECT MaCuaHang FROM Kho, NhanVien WHERE MaNhanVien = @TRUONGKHO AND NhanVien.CuaHang = @CUAHANG)
	BEGIN
		DECLARE @CH CHAR(10) = (SELECT MaCuaHang FROM Kho, NhanVien WHERE MaNhanVien = @TRUONGKHO AND Kho.MaCuaHang = NhanVien.CuaHang)
		DECLARE @DEMKHO INT = (SELECT COUNT(MaKho) FROM Kho)
		DECLARE @I INT = 0
		SET @DEMKHO += 1
		DECLARE @ID CHAR(5)

		DECLARE @CHUOISOKHONG VARCHAR(4) = '0'
		DECLARE @LENGTHID INT = 5 - (LEN('K') + LEN(@DEMKHO))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END

		SET @ID  = CONCAT('K',@CHUOISOKHONG,@DEMKHO)
		DECLARE @DEMID INT = (SELECT COUNT(MaKho) FROM Kho WHERE MaKho = @ID)

		WHILE(@DEMID <> 0)
		BEGIN
			SET @DEMKHO += 1
			SET @CHUOISOKHONG = '0'
			SET @ID = 0
			SET @LENGTHID = 5 - (LEN('K') + LEN(@DEMKHO))

			WHILE(@I < @LENGTHID - 1)
			BEGIN
				SET @CHUOISOKHONG += '0'
				SET @I += 1
			END
			SET @ID  = CONCAT('K',@CHUOISOKHONG,@DEMKHO)
			SET @DEMID = (SELECT COUNT(MaKho) FROM Kho WHERE MaKho = @DEMKHO)
		END
		BEGIN TRAN
		BEGIN TRY
			INSERT INTO Kho(MaKho,MaCuaHang,TruongKho,DiaChi)
			VALUES(@ID,@CUAHANG,@TRUONGKHO,@DIACHI)
			COMMIT
		END TRY
		BEGIN CATCH
			ROLLBACK
			DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
			RAISERROR(@ERRORMESS,16,1)
		END CATCH
	END
	ELSE
		RAISERROR('Mã nhân viên trưởng kho không trực thuộc cửa hàng! Đổi nhân viên khác',16,1)
END
GO

---Tao ID cho PHIEUNHAP---
CREATE TRIGGER TAO_ID_CHO_PHIEU_NHAP ON PhieuNhap INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @NCC CHAR(5) = (SELECT NhaCungCap FROM inserted)
	DECLARE @NVTRUCKHO CHAR(10) = (SELECT NhanVienTrucKho  FROM inserted)
	DECLARE @MAKHO CHAR(5) = (SELECT MaKho  FROM inserted)
	DECLARE @THOIGIANTAO DATETIME = (SELECT ThoiGianTao FROM inserted)
	DECLARE @TrangThai BIT = (SELECT TrangThai FROM PhieuNhap)
	IF((SELECT MaCuaHang FROM Kho WHERE MaKho = @MAKHO) <> (SELECT CuaHang FROM NhanVien WHERE MaNhanVien = @NVTRUCKHO))
	BEGIN
		ROLLBACK
		RAISERROR(N'Lỗi: Mã nhân viên không trực thuộc kho này!! Mã nhân viên thuộc cửa hàng khác.)',16,1)
	END
	ELSE
	BEGIN
			DECLARE @DEMPN INT = (SELECT COUNT(MaPhieuNhap) FROM PhieuNhap)
		DECLARE @I INT = 0
		SET @DEMPN += 1
		DECLARE @ID CHAR(10)

		DECLARE @CHUOISOKHONG VARCHAR(8) = '0'
		DECLARE @LENGTHID INT = 10 - (LEN('PN') + LEN(@DEMPN))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END

		SET @ID  = CONCAT('PN',@CHUOISOKHONG,@DEMPN)
		DECLARE @DEMID INT = (SELECT COUNT(MaPhieuNhap) FROM PhieuNhap WHERE MaPhieuNhap = @ID)

		WHILE(@DEMID <> 0)
		BEGIN
			SET @DEMPN += 1
			SET @CHUOISOKHONG = '0'
			SET @ID = 0
			SET @LENGTHID = 10 - (LEN('PN') + LEN(@DEMPN))

			WHILE(@I < @LENGTHID - 1)
			BEGIN
				SET @CHUOISOKHONG += '0'
				SET @I += 1
			END
			SET @ID  = CONCAT('PN',@CHUOISOKHONG,@DEMPN)
			SET @DEMID = (SELECT COUNT(MaPhieuNhap) FROM PhieuNhap WHERE MaPhieuNhap = @DEMPN)
		END
		BEGIN TRAN
		BEGIN TRY
			INSERT INTO PhieuNhap(MaPhieuNhap, NhaCungCap,NhanVienTrucKho,MaKho,ThoiGianTao)
			VALUES(@ID,@NCC,@NVTRUCKHO,@MAKHO,@THOIGIANTAO)
			COMMIT
		END TRY
		BEGIN CATCH
			ROLLBACK
			DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
			RAISERROR(@ERRORMESS,16,1)
		END CATCH
	END
END
GO
---Nhap KHO---
CREATE TRIGGER NHAP_HANG_VAO_KHO ON ChiTietPhieuNhap AFTER INSERT
AS
BEGIN
	DECLARE @MAPN CHAR(10) = (SELECT MaPhieuNhap FROM inserted)
	DECLARE @MAKHO CHAR(5) = (SELECT MaKho FROM PhieuNhap WHERE MaPhieuNhap = @MAPN)
	DECLARE @MASP CHAR(10) = (SELECT MaSanPham FROM inserted)
	DECLARE @SLNHAP INT = (SELECT SoLuong FROM inserted)
	DECLARE @DONGIA DECIMAL(18,2) = (SELECT DonGiaNhap FROM inserted)
	BEGIN TRAN
	BEGIN TRY
		UPDATE ChiTietKho SET SoLuong = SoLuong + @SLNHAP WHERE MaKho = @MAKHO AND MaSanPham = @MASP
		UPDATE PhieuNhap SET TongGiaTri = TongGiaTri + (@SLNHAP * @DONGIA)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID cho KhachHang---
CREATE TRIGGER TAO_ID_CHO_KHACH_HANG ON KhachHang INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @tenKhachHang NVARCHAR(50) = (SELECT TenKhachHang FROM inserted)
	DECLARE @sDT CHAR(10) = (SELECT SDT FROM inserted)
	DECLARE @diaChi NVARCHAR(100) = (SELECT DiaChi FROM inserted)
	DECLARE @thanhPho NVARCHAR(100) = (SELECT ThanhPho FROM inserted)
	DECLARE @email CHAR(50) = (SELECT Email FROM inserted)
	DECLARE @taiKhoan CHAR(50) = (SELECT TaiKhoan FROM inserted)
	DECLARE @matKhau CHAR(50) = (SELECT MatKhau FROM inserted)
	DECLARE @trangThai BIT = (SELECT TrangThai FROM inserted)

	DECLARE @DEMKH INT = (SELECT COUNT(MaKhachHang) FROM KhachHang)
	DECLARE @I INT = 0
	SET @DEMKH += 1
	DECLARE @ID CHAR(10)

	DECLARE @chuoiSoKhong VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('KH') + LEN(@DEMKH))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('KH',@chuoiSoKhong,@DEMKH)
	DECLARE @DEMID INT = (SELECT COUNT(MaKhachHang) FROM KhachHang WHERE MaKhachHang = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMKH += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('KH') + LEN(@DEMKH))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('KH',@chuoiSoKhong,@DEMKH)
		SET @DEMID = (SELECT COUNT(MaKhachHang) FROM KhachHang WHERE MaKhachHang = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO KhachHang(MaKhachHang,TenKhachHang,SDT,DiaChi,ThanhPho,Email,TaiKhoan,MatKhau,TrangThai)
		VALUES(@ID,@tenKhachHang,@sDT,@diaChi,@thanhPho,@email,@taiKhoan,@matKhau,@trangThai)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID cho Voucher---
/*CREATE TRIGGER TAO_ID_CHO_VOUCHER ON Voucher INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @tenVoucher NVARCHAR(50) = (SELECT TenVoucher FROM inserted)
	DECLARE @phanTramKhuyenMai FLOAT = (SELECT PhanTramKhuyenMai FROM inserted)
	DECLARE @ngayBatDau DATETIME = (SELECT NgayBatDau FROM inserted)
	DECLARE @ngayKetThuc DATETIME = (SELECT NgayKetThuc FROM inserted)
	DECLARE @moTa NVARCHAR(50) = (SELECT MoTa FROM inserted)

	DECLARE @DEMVC INT = (SELECT COUNT(MaVoucher) FROM Voucher)
	DECLARE @I INT = 0
	SET @DEMVC += 1
	DECLARE @ID CHAR(10)

	DECLARE @chuoiSoKhong VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('VC') + LEN(@DEMVC))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('VC',@chuoiSoKhong,@DEMVC)
	DECLARE @DEMID INT = (SELECT COUNT(MaVoucher) FROM Voucher WHERE MaVoucher = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMVC += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('VC') + LEN(@DEMVC))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('VC',@chuoiSoKhong,@DEMVC)
		SET @DEMID = (SELECT COUNT(MaVoucher) FROM Voucher WHERE MaVoucher = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO Voucher(MaVoucher,TenVoucher,PhanTramKhuyenMai,NgayBatDau,NgayKetThuc,MoTa)
		VALUES(@ID,@tenVoucher,@phanTramKhuyenMai,@ngayBatDau,@ngayKetThuc,@moTa)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
*/
---Tao ID cho Voucher---
/*
CREATE TRIGGER TAO_ID_CHO_DON_HANG ON DonHang INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @nhanVienPhuTrach CHAR(10) = (SELECT NhanVienPhuTrach FROM inserted)
	DECLARE @maKhachHang CHAR(10) = (SELECT MaKhachHang FROM inserted)
	DECLARE @maCuaHang CHAR(5) = (SELECT MaCuaHang FROM inserted)
	DECLARE @thoiGianTao DATETIME = (SELECT ThoiGianTao FROM inserted)
	DECLARE @maVoucher CHAR(10) = (SELECT MaVoucher FROM inserted)
	DECLARE @loai BIT = (SELECT Loai FROM inserted)
	DECLARE @tinhTrangXacNhan BIT = (SELECT TinhTrangXacNhan FROM inserted)
	DECLARE @tinhTrangThanhToan BIT = (SELECT TinhTrangThanhToan FROM inserted)
	DECLARE @tinhTrangGiaoHang BIT = (SELECT TinhTrangGiaoHang FROM inserted)

	DECLARE @DEMDH INT = (SELECT COUNT(MaDonHang) FROM DonHang)
	DECLARE @I INT = 0
	SET @DEMDH += 1
	DECLARE @ID CHAR(10)

	DECLARE @chuoiSoKhong VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('DH') + LEN(@DEMDH))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('DH',@chuoiSoKhong,@DEMDH)
	DECLARE @DEMID INT = (SELECT COUNT(MaVoucher) FROM Voucher WHERE MaVoucher = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMDH += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('DH') + LEN(@DEMDH))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('DH',@chuoiSoKhong,@DEMDH)
		SET @DEMID = (SELECT COUNT(MaVoucher) FROM Voucher WHERE MaVoucher = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO DonHang(MaDonHang,NhanVienPhuTrach,MaKhachHang,MaCuaHang,ThoiGianTao,MaVoucher,Loai,TinhTrangXacNhan,TinhTrangThanhToan,TinhTrangGiaoHang)
		VALUES(@ID,@nhanVienPhuTrach,@maKhachHang,@maCuaHang,@thoiGianTao,@maVoucher,@loai,@tinhTrangXacNhan,@tinhTrangThanhToan,@tinhTrangGiaoHang)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO
*/
---Tao ID cho HangTichDiem---

CREATE TRIGGER TAO_ID_CHO_HANG_TICH_DIEM ON HangTichDiem INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @tenHang NVARCHAR(20) = (SELECT TenHang FROM inserted)

	DECLARE @DEMHANG INT = (SELECT COUNT(MaHang) FROM HangTichDiem)
	DECLARE @I INT = 0
	SET @DEMHANG += 1
	DECLARE @ID CHAR(5)

	DECLARE @chuoiSoKhong VARCHAR(4) = '0'
	DECLARE @LENGTHID INT = 5 - (LEN('H') + LEN(@DEMHANG))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('H',@chuoiSoKhong,@DEMHANG)
	DECLARE @DEMID INT = (SELECT COUNT(MaHang) FROM HangTichDiem WHERE MaHang = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMHANG += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 5 - (LEN('H') + LEN(@DEMHANG))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('H',@chuoiSoKhong,@DEMHANG)
		SET @DEMID = (SELECT COUNT(MaHang) FROM HangTichDiem WHERE MaHang = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO HangTichDiem(MaHang,TenHang)
		VALUES(@ID,@tenHang)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID cho TheTichDiem---

CREATE TRIGGER TAO_ID_CHO_THE_TICH_DIEM ON TheTichDiem INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @maKhacHang CHAR(10) = (SELECT MaKhachHang FROM inserted)

	IF EXISTS(SELECT(MaKhachHang) FROM TheTichDiem WHERE MaKhachHang = @maKhacHang)
	BEGIN
		RAISERROR('Khách hàng đã có thẻ tích điểm',16,1)
	END
	ELSE
	BEGIN
		DECLARE @maHang CHAR(5) = (SELECT Hang FROM inserted)
		DECLARE @ngayTao DATETIME = (SELECT NgayTao FROM inserted)
		DECLARE @diem INT = (SELECT Diem FROM inserted)
		DECLARE @trangThai BIT = (SELECT TrangThai FROM inserted)

		DECLARE @DEMTHE INT = (SELECT COUNT(MaThe) FROM TheTichDiem)
		DECLARE @I INT = 0
		SET @DEMTHE += 1
		DECLARE @ID CHAR(10)

		DECLARE @chuoiSoKhong VARCHAR(10) = '0'
		DECLARE @LENGTHID INT = 10 - (LEN('T') + LEN(@DEMTHE))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END

		SET @ID  = CONCAT('T',@chuoiSoKhong,@DEMTHE)
		DECLARE @DEMID INT = (SELECT COUNT(MaThe) FROM TheTichDiem WHERE MaThe = @ID)

		WHILE(@DEMID <> 0)
		BEGIN
			SET @DEMTHE += 1
			SET @CHUOISOKHONG = '0'
			SET @ID = 0
			SET @LENGTHID = 10 - (LEN('T') + LEN(@DEMTHE))

			WHILE(@I < @LENGTHID - 1)
			BEGIN
				SET @CHUOISOKHONG += '0'
				SET @I += 1
			END
			SET @ID  = CONCAT('T',@chuoiSoKhong,@DEMTHE)
			SET @DEMID = (SELECT COUNT(MaThe) FROM TheTichDiem WHERE MaThe = @ID)
		END
		BEGIN TRAN
		BEGIN TRY
			INSERT INTO TheTichDiem(MaThe,MaKhachHang,Hang,NgayTao,Diem,TrangThai)
			VALUES(@ID,@maKhacHang,@maHang,@ngayTao,@diem,@trangThai)
			COMMIT
		END TRY
		BEGIN CATCH
			ROLLBACK
			DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
			RAISERROR(@ERRORMESS,16,1)
		END CATCH
	END	
END
GO


---Tao ID cho PhieuXuat---

CREATE TRIGGER TAO_ID_PHIEU_XUAT ON PhieuXuat INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @nhan_vien_tao_phieu CHAR(10) = (SELECT NhanVienTaoPhieu FROM inserted)
	DECLARE @nhan_vien_truong_kho CHAR(10) = (SELECT NhanVienTruongKho FROM inserted)
	DECLARE @ma_kho CHAR(5) = (SELECT MaKho FROM inserted)
	DECLARE @ma_don_hang CHAR(10) = (SELECT MaDonHang FROM inserted)
	DECLARE @thoi_gian_tao DATETIME = (SELECT ThoiGianTao FROM inserted)
	DECLARE @tong_gia_tri DECIMAL(18,2) = (SELECT TongGiaTri FROM inserted)
	DECLARE @trang_thai BIT = (SELECT TrangThai FROM inserted) 

	DECLARE @DEMPX INT = (SELECT COUNT(MaPhieuXuat) FROM PhieuXuat)
	DECLARE @I INT = 0
	SET @DEMPX += 1
	DECLARE @ID CHAR(10)

	DECLARE @chuoiSoKhong VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('PX') + LEN(@DEMPX))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('PX',@chuoiSoKhong,@DEMPX)
	DECLARE @DEMID INT = (SELECT COUNT(MaPhieuXuat) FROM PhieuXuat WHERE MaPhieuXuat = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMPX += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('PX') + LEN(@DEMPX))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('PX',@chuoiSoKhong,@DEMPX)
		SET @DEMID = (SELECT COUNT(MaPhieuXuat) FROM PhieuXuat WHERE MaPhieuXuat = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO PhieuXuat(MaPhieuXuat,NhanVienTaoPhieu,NhanVienTruongKho,MaKho,MaDonHang,ThoiGianTao,TongGiaTri,TrangThai)
		VALUES(@ID,@nhan_vien_tao_phieu,@nhan_vien_truong_kho,@ma_kho,@ma_don_hang,@thoi_gian_tao,@tong_gia_tri, @trang_thai)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO

---Tao ID cho PhieuBaoHanh---

CREATE TRIGGER TAO_ID_PHIEU_BAO_HANH ON PhieuBaoHanh INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @ma_san_pham CHAR(10) = (SELECT MaSanPham FROM inserted)
	DECLARE @ma_khach_hang CHAR(10) = (SELECT MaKhachHang FROM inserted)
	DECLARE @ma_don_hang CHAR(10) = (SELECT MaDonHang FROM inserted)
	DECLARE @ngay_tao DATETIME = (SELECT NgayTao FROM inserted)
	DECLARE @ngay_het_han DATETIME = (SELECT NgayHetHan FROM inserted)
	DECLARE @trang_thai BIT = (SELECT TrangThai FROM inserted) 

	DECLARE @DEMPBH INT = (SELECT COUNT(MaPhieuBH) FROM PhieuBaoHanh)
	DECLARE @I INT = 0
	SET @DEMPBH += 1
	DECLARE @ID CHAR(10)

	DECLARE @chuoiSoKhong VARCHAR(8) = '0'
	DECLARE @LENGTHID INT = 10 - (LEN('BH') + LEN(@DEMPBH))

	WHILE(@I < @LENGTHID - 1)
	BEGIN
		SET @CHUOISOKHONG += '0'
		SET @I += 1
	END

	SET @ID  = CONCAT('BH',@chuoiSoKhong,@DEMPBH)
	DECLARE @DEMID INT = (SELECT COUNT(MaPhieuBH) FROM PhieuBaoHanh WHERE MaPhieuBH = @ID)

	WHILE(@DEMID <> 0)
	BEGIN
		SET @DEMPBH += 1
		SET @CHUOISOKHONG = '0'
		SET @ID = 0
		SET @LENGTHID = 10 - (LEN('BH') + LEN(@DEMPBH))

		WHILE(@I < @LENGTHID - 1)
		BEGIN
			SET @CHUOISOKHONG += '0'
			SET @I += 1
		END
		SET @ID  = CONCAT('BH',@chuoiSoKhong,@DEMPBH)
		SET @DEMID = (SELECT COUNT(MaPhieuBH) FROM PhieuBaoHanh WHERE MaPhieuBH = @ID)
	END
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO PhieuBaoHanh(MaPhieuBH,MaSanPham,MaKhachHang,MaDonHang,NgayTao,NgayHetHan,TrangThai)
		VALUES(@ID,@ma_san_pham,@ma_khach_hang,@ma_don_hang,@ngay_tao,@ngay_het_han, @trang_thai)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERRORMESS VARCHAR(2000) = 'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERRORMESS,16,1)
	END CATCH
END
GO