//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_95F0C05A250749C193F5A538AD67F037
    {
        public string MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
