//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_ctsv_D9E091456FAE4AB185849640C91F03BB
    {
        public int tablenick { get; set; }
        public System.Guid rowguid { get; set; }
        public long generation { get; set; }
        public Nullable<long> partchangegen { get; set; }
        public byte[] lineage { get; set; }
        public byte[] colv1 { get; set; }
        public Nullable<System.Guid> marker { get; set; }
        public Nullable<System.Guid> logical_record_parent_rowguid { get; set; }
        public byte[] logical_record_lineage { get; set; }
    }
}
