//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_ppmv_F39BD2298472454F9C0FE02D795211B0
    {
        public short publication_number { get; set; }
        public int tablenick { get; set; }
        public System.Guid rowguid { get; set; }
        public int partition_id { get; set; }
        public Nullable<long> generation { get; set; }
        public byte reason { get; set; }
    }
}
