//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_F2597FEE354C4E1A830E168382EDB99F
    {
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaThuongHieu { get; set; }
        public string AnhMinhHoa { get; set; }
        public decimal DonGia { get; set; }
        public string MaKhuyenMai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
