//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_3B119D6CCA384A37AAD74B2C42C4FA58
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
