//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_D9E091456FAE4AB185849640C91F03BB
    {
        public string MaPhanHoi { get; set; }
        public string MaKhachHang { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
