//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_A66B25AFE51348DFB9AF6378E073C436
    {
        public string MaPhieuNhap { get; set; }
        public string NhaCungCap { get; set; }
        public string NhanVienTrucKho { get; set; }
        public string MaKho { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
