//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_ABD8B1EDB0E84A73816055D7FAE25E8B
    {
        public string MaThanhPho { get; set; }
        public string TenThanhPho { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
