//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_C2F34DE67FB1426985C16D21CD5128AE
    {
        public string MaKho { get; set; }
        public string MaCuaHang { get; set; }
        public string DiaChi { get; set; }
        public string TruongKho { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
