//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_9E6D847CD4B84C1494FB744C73333224
    {
        public string MaCuaHang { get; set; }
        public string DiaChi { get; set; }
        public string CuaHangTruong { get; set; }
        public Nullable<System.DateTime> NgayThanhLap { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
