//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_QLDienMay_CN2_TheTichDiem_VIEW
    {
        public string MaThe { get; set; }
        public string MaKhachHang { get; set; }
        public string Hang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
