//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_C0541825B4094DAE9C4111318E45616B
    {
        public string MaPhieuXuat { get; set; }
        public string NhanVienTaoPhieu { get; set; }
        public string NhanVienTruongKho { get; set; }
        public string MaKho { get; set; }
        public string MaDonHang { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
