//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_B234B6FE02564F9EB38BAD96BCB2134A
    {
        public string MaSanPham { get; set; }
        public string MaLoai { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
