//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_FD93D890BE1F46179C05EA77DA67C3C7_908276E0587D4863B9837BE92F24AFD5
    {
        public string MaDonHang { get; set; }
        public string NhanVienPhuTrach { get; set; }
        public string MaKhachHang { get; set; }
        public string MaCuaHang { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public string MaVoucher { get; set; }
        public Nullable<bool> Loai { get; set; }
        public Nullable<bool> TinhTrangXacNhan { get; set; }
        public Nullable<bool> TinhTrangThanhToan { get; set; }
        public Nullable<bool> TinhTrangGiaoHang { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
