//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_tsvw_9D2B1E57F6EA4640855AC2F0DDC38569
    {
        public System.Guid rowguid { get; set; }
        public int tablenick { get; set; }
        public byte type { get; set; }
        public byte[] lineage { get; set; }
        public long generation { get; set; }
        public Nullable<System.Guid> logical_record_parent_rowguid { get; set; }
        public byte[] logical_record_lineage { get; set; }
    }
}
