//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_repl_view_91A90624B30540B8A9D5136E5E47D25C_897154BD00094B28AF9013C540B937CB
    {
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MaDanhMuc { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
