//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_genvw_C2F34DE67FB1426985C16D21CD5128AE
    {
        public System.Guid guidsrc { get; set; }
        public Nullable<System.Guid> pubid { get; set; }
        public long generation { get; set; }
        public Nullable<int> art_nick { get; set; }
        public byte[] nicknames { get; set; }
        public System.DateTime coldate { get; set; }
        public byte genstatus { get; set; }
        public int changecount { get; set; }
        public int subscriber_number { get; set; }
    }
}
