//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public string MaPhieuNhap { get; set; }
        public string NhaCungCap { get; set; }
        public string NhanVienTrucKho { get; set; }
        public string MaKho { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NhaCungCap NhaCungCap1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
