//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDienMayEntities1 : DbContext
    {
        public QLDienMayEntities1()
            : base("name=QLDienMayEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietKho> ChiTietKhoes { get; set; }
        public virtual DbSet<ChiTietLoai> ChiTietLoais { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CuaHang> CuaHangs { get; set; }
        public virtual DbSet<DacDiemNoiBat> DacDiemNoiBats { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<HangTichDiem> HangTichDiems { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<MSdynamicsnapshotview> MSdynamicsnapshotviews { get; set; }
        public virtual DbSet<MSmerge_dynamic_snapshots> MSmerge_dynamic_snapshots { get; set; }
        public virtual DbSet<MSmerge_partition_groups> MSmerge_partition_groups { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanHoi> PhanHois { get; set; }
        public virtual DbSet<PhieuBaoHanh> PhieuBaoHanhs { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysreplserver> sysreplservers { get; set; }
        public virtual DbSet<TheTichDiem> TheTichDiems { get; set; }
        public virtual DbSet<ThongSoKiThuat> ThongSoKiThuats { get; set; }
        public virtual DbSet<TinhNang> TinhNangs { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<MSdynamicsnapshotjob> MSdynamicsnapshotjobs { get; set; }
        public virtual DbSet<MSmerge_agent_parameters> MSmerge_agent_parameters { get; set; }
        public virtual DbSet<MSmerge_altsyncpartners> MSmerge_altsyncpartners { get; set; }
        public virtual DbSet<MSmerge_articlehistory> MSmerge_articlehistory { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChiTietDonHang> MSmerge_conflict_QLDienMay_CN1_ChiTietDonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChiTietKho> MSmerge_conflict_QLDienMay_CN1_ChiTietKho { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChiTietLoai> MSmerge_conflict_QLDienMay_CN1_ChiTietLoai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChiTietPhieuNhap> MSmerge_conflict_QLDienMay_CN1_ChiTietPhieuNhap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChiTietPhieuXuat> MSmerge_conflict_QLDienMay_CN1_ChiTietPhieuXuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ChucVu> MSmerge_conflict_QLDienMay_CN1_ChucVu { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_CuaHang> MSmerge_conflict_QLDienMay_CN1_CuaHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_DacDiemNoiBat> MSmerge_conflict_QLDienMay_CN1_DacDiemNoiBat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_DanhMuc> MSmerge_conflict_QLDienMay_CN1_DanhMuc { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_DonHang> MSmerge_conflict_QLDienMay_CN1_DonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_HangTichDiem> MSmerge_conflict_QLDienMay_CN1_HangTichDiem { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_KhachHang> MSmerge_conflict_QLDienMay_CN1_KhachHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_Kho> MSmerge_conflict_QLDienMay_CN1_Kho { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_KhuyenMai> MSmerge_conflict_QLDienMay_CN1_KhuyenMai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_Loai> MSmerge_conflict_QLDienMay_CN1_Loai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_NhaCungCap> MSmerge_conflict_QLDienMay_CN1_NhaCungCap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_NhanVien> MSmerge_conflict_QLDienMay_CN1_NhanVien { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_PhanHoi> MSmerge_conflict_QLDienMay_CN1_PhanHoi { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_PhieuBaoHanh> MSmerge_conflict_QLDienMay_CN1_PhieuBaoHanh { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_PhieuNhap> MSmerge_conflict_QLDienMay_CN1_PhieuNhap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_PhieuXuat> MSmerge_conflict_QLDienMay_CN1_PhieuXuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_SanPham> MSmerge_conflict_QLDienMay_CN1_SanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_TheTichDiem> MSmerge_conflict_QLDienMay_CN1_TheTichDiem { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_ThongSoKiThuat> MSmerge_conflict_QLDienMay_CN1_ThongSoKiThuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_TinhNang> MSmerge_conflict_QLDienMay_CN1_TinhNang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN1_Voucher> MSmerge_conflict_QLDienMay_CN1_Voucher { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChiTietDonHang> MSmerge_conflict_QLDienMay_CN2_ChiTietDonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChiTietKho> MSmerge_conflict_QLDienMay_CN2_ChiTietKho { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChiTietLoai> MSmerge_conflict_QLDienMay_CN2_ChiTietLoai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChiTietPhieuNhap> MSmerge_conflict_QLDienMay_CN2_ChiTietPhieuNhap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChiTietPhieuXuat> MSmerge_conflict_QLDienMay_CN2_ChiTietPhieuXuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ChucVu> MSmerge_conflict_QLDienMay_CN2_ChucVu { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_CuaHang> MSmerge_conflict_QLDienMay_CN2_CuaHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_DacDiemNoiBat> MSmerge_conflict_QLDienMay_CN2_DacDiemNoiBat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_DanhMuc> MSmerge_conflict_QLDienMay_CN2_DanhMuc { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_DonHang> MSmerge_conflict_QLDienMay_CN2_DonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_HangTichDiem> MSmerge_conflict_QLDienMay_CN2_HangTichDiem { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_KhachHang> MSmerge_conflict_QLDienMay_CN2_KhachHang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_Kho> MSmerge_conflict_QLDienMay_CN2_Kho { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_KhuyenMai> MSmerge_conflict_QLDienMay_CN2_KhuyenMai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_Loai> MSmerge_conflict_QLDienMay_CN2_Loai { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_NhaCungCap> MSmerge_conflict_QLDienMay_CN2_NhaCungCap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_NhanVien> MSmerge_conflict_QLDienMay_CN2_NhanVien { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_PhanHoi> MSmerge_conflict_QLDienMay_CN2_PhanHoi { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_PhieuBaoHanh> MSmerge_conflict_QLDienMay_CN2_PhieuBaoHanh { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_PhieuNhap> MSmerge_conflict_QLDienMay_CN2_PhieuNhap { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_PhieuXuat> MSmerge_conflict_QLDienMay_CN2_PhieuXuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_SanPham> MSmerge_conflict_QLDienMay_CN2_SanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_TheTichDiem> MSmerge_conflict_QLDienMay_CN2_TheTichDiem { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_ThongSoKiThuat> MSmerge_conflict_QLDienMay_CN2_ThongSoKiThuat { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_TinhNang> MSmerge_conflict_QLDienMay_CN2_TinhNang { get; set; }
        public virtual DbSet<MSmerge_conflict_QLDienMay_CN2_Voucher> MSmerge_conflict_QLDienMay_CN2_Voucher { get; set; }
        public virtual DbSet<MSmerge_conflicts_info> MSmerge_conflicts_info { get; set; }
        public virtual DbSet<MSmerge_contents> MSmerge_contents { get; set; }
        public virtual DbSet<MSmerge_current_partition_mappings> MSmerge_current_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_errorlineage> MSmerge_errorlineage { get; set; }
        public virtual DbSet<MSmerge_generation_partition_mappings> MSmerge_generation_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_genhistory> MSmerge_genhistory { get; set; }
        public virtual DbSet<MSmerge_history> MSmerge_history { get; set; }
        public virtual DbSet<MSmerge_identity_range> MSmerge_identity_range { get; set; }
        public virtual DbSet<MSmerge_log_files> MSmerge_log_files { get; set; }
        public virtual DbSet<MSmerge_metadataaction_request> MSmerge_metadataaction_request { get; set; }
        public virtual DbSet<MSmerge_past_partition_mappings> MSmerge_past_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_replinfo> MSmerge_replinfo { get; set; }
        public virtual DbSet<MSmerge_sessions> MSmerge_sessions { get; set; }
        public virtual DbSet<MSmerge_settingshistory> MSmerge_settingshistory { get; set; }
        public virtual DbSet<MSmerge_supportability_settings> MSmerge_supportability_settings { get; set; }
        public virtual DbSet<MSmerge_tombstone> MSmerge_tombstone { get; set; }
        public virtual DbSet<MSrepl_errors> MSrepl_errors { get; set; }
        public virtual DbSet<sysmergearticle> sysmergearticles { get; set; }
        public virtual DbSet<sysmergepartitioninfo> sysmergepartitioninfoes { get; set; }
        public virtual DbSet<sysmergepublication> sysmergepublications { get; set; }
        public virtual DbSet<sysmergeschemaarticle> sysmergeschemaarticles { get; set; }
        public virtual DbSet<sysmergeschemachange> sysmergeschemachanges { get; set; }
        public virtual DbSet<sysmergesubscription> sysmergesubscriptions { get; set; }
        public virtual DbSet<sysmergesubsetfilter> sysmergesubsetfilters { get; set; }
    
        public virtual ObjectResult<string> sp_DangNhap(string taiKhoan, string matKhau, Nullable<int> type)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DangNhap", taiKhoanParameter, matKhauParameter, typeParameter);
        }
    }
}
